spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      database: mysql
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3308/demo?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

server:
  port: 8080
